trigger:
- main

variables:
- group: TESTE

pool:
  vmImage: ubuntu-latest

stages:
- stage: CD
  displayName: "CD"
  jobs:
  - job: DeployJob
    displayName: "Deployment Job"
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: docker
      displayName: 'Run a one-line script'

    - script: |
        echo "Usando a variável TESTE_VAR do grupo de variáveis"
        echo $(TESTE_VAR)
      displayName: 'Run a multi-line script'
