name: Pipeline com Aprovação Manual

on:
  workflow_dispatch:

jobs:
  etapa1:
    name: Etapa 1 - Início
    runs-on: ubuntu-latest
    environment: etapa-1-aprovacao
    steps:
      - name: Executando Etapa 1
        run: echo "Etapa 1 concluída"

  etapa2:
    name: Etapa 2 - Processamento
    runs-on: ubuntu-latest
    needs: etapa1
    environment: etapa-2-aprovacao
    steps:
      - name: Executando Etapa 2
        run: echo "Etapa 2 concluída"

  etapa3:
    name: Etapa 3 - Finalização
    runs-on: ubuntu-latest
    needs: etapa2
    environment: etapa-3-aprovacao
    steps:
      - name: Executando Etapa 3
        run: echo "Etapa 3 concluída"
