name: Worlflow Evento
on:
  pull_request:
    branches: ["main"]
jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Action de teste
              run: echo "Action executad apenas nas branches main e feature/*"