name: Pipeline com Aprovações

on:
  workflow_dispatch:

jobs:
  stage1:
    name: Etapa 1 - Início
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem
        run: echo "Executando a Etapa 1"

  approval1:
    name: Aprovação para Etapa 2
    needs: stage1
    runs-on: ubuntu-latest
    environment:
      name: aprovacao-etapa-2
      url: https://github.com
    steps:
      - name: Aguardando aprovação para Etapa 2
        run: echo "Aguardando aprovação manual..."

  stage2:
    name: Etapa 2 - Processamento
    needs: approval1
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem
        run: echo "Executando a Etapa 2"

  approval2:
    name: Aprovação para Etapa 3
    needs: stage2
    runs-on: ubuntu-latest
    environment:
      name: aprovacao-etapa-3
      url: https://github.com
    steps:
      - name: Aguardando aprovação para Etapa 3
        run: echo "Aguardando aprovação manual..."

  stage3:
    name: Etapa 3 - Finalização
    needs: approval2
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem
        run: echo "Executando a Etapa 3"
